name: pytest

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      # 跑测试
      - name: Run pytest
        run: uv run pytest -p no:launch_testing -v