name: qtdata_data
description: 量潮数据流程组件包（Pipeline/Task 展示 Widgets + Bloc 状态管理）
version: 0.1.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  flutter_bloc: ^9.1.0
  quanttide_data: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
